### ISSUE TITLE
Task - Research the URL for Site

### ISSUE THREAD

**Issue by yehk** [18F/data-act-usaspending#26]

**Comment by msathyaraj2015** [comment]
The process for securing the URL is as follows: 
1.  The CIO from BPD will need to send the Treasury of the CIO a memo requesting the domain.  This will, if expedited, will take about two weeks.
2.  Once this is completed and permission granted, Lee will help us secure the Domain through www.dotgov.gov. 
3.  Upon completion of that the DNS will need be registered which is a much easier task since it is internal.
